base_model: bjoernp/micro-bitllama
trust_remote_code: True

model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

max_steps: 1000
datasets:
  - path: bjoernp/tagesschau_pretrain
    type: completion

dataset_prepared_path:
val_set_size: 0.01
output_dir: ./model-out

sequence_len: 512
sample_packing: false

wandb_project: bitllama
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 64
num_epochs: 1
optimizer: adamw_hf
lr_scheduler: cosine
learning_rate: 0.00015

train_on_inputs: true
group_by_length: false
bf16:
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
evals_per_epoch:
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.01
fsdp:
fsdp_config:
special_tokens:
